homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named configurations/packages

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

scene: !include scenes.yaml

openhasp: !include configurations/plates/openhasp.yaml

lovelace:
  mode: storage
  dashboards:
    gartenwasser-dashboard:
      mode: yaml
      title: Gartenwasser
      icon: mdi:sprinkler-variant
      show_in_sidebar: true
      filename: dashboards/gartenwasser.yaml
