homeassistant:
  customize: !include customize.yaml

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

script: !include scripts.yaml
scene: !include scenes.yaml

input_number: !include configurations/input_number.yaml
automation: !include configurations/automations.yaml
openhasp: !include configurations/openHASP.yaml
mqtt: !include configurations/mqtt.yaml
